const state = {
  data: [
    {
      "Brand": "100%_Bran",
      "Energy": "N",
      "Protein": 70,
      "Fat": 4,
      "Na": 1,
      "Fiber": 130,
      "Carbs": 10,
      "Sugar": 5,
      "K": 6,
      "Vit": 280,
      "Score": 25
    },
    {
      "Brand": "100%_Natural_Bran",
      "Energy": "Q",
      "Protein": 120,
      "Fat": 3,
      "Na": 5,
      "Fiber": 15,
      "Carbs": 2,
      "Sugar": 8,
      "K": 8,
      "Vit": 135,
      "Score": 0
    },
    {
      "Brand": "All-Bran",
      "Energy": "K",
      "Protein": 70,
      "Fat": 4,
      "Na": 1,
      "Fiber": 260,
      "Carbs": 9,
      "Sugar": 7,
      "K": 5,
      "Vit": 320,
      "Score": 25
    },
    {
      "Brand": "All-Bran_with_Extra_Fiber",
      "Energy": "K",
      "Protein": 50,
      "Fat": 4,
      "Na": 0,
      "Fiber": 140,
      "Carbs": 14,
      "Sugar": 8,
      "K": 0,
      "Vit": 330,
      "Score": 25
    },
    {
      "Brand": "Apple_Cinnamon_Cheerios",
      "Energy": "G",
      "Protein": 110,
      "Fat": 2,
      "Na": 2,
      "Fiber": 180,
      "Carbs": 1.5,
      "Sugar": 10.5,
      "K": 10,
      "Vit": 70,
      "Score": 25
    },
    {
      "Brand": "Apple_Jacks",
      "Energy": "K",
      "Protein": 110,
      "Fat": 2,
      "Na": 0,
      "Fiber": 125,
      "Carbs": 1,
      "Sugar": 11,
      "K": 14,
      "Vit": 30,
      "Score": 25
    },
    {
      "Brand": "Basic_4",
      "Energy": "G",
      "Protein": 130,
      "Fat": 3,
      "Na": 2,
      "Fiber": 210,
      "Carbs": 2,
      "Sugar": 18,
      "K": 8,
      "Vit": 100,
      "Score": 25
    },
    {
      "Brand": "Bran_Chex",
      "Energy": "R",
      "Protein": 90,
      "Fat": 2,
      "Na": 1,
      "Fiber": 200,
      "Carbs": 4,
      "Sugar": 15,
      "K": 6,
      "Vit": 125,
      "Score": 25
    },
    {
      "Brand": "Bran_Flakes",
      "Energy": "P",
      "Protein": 90,
      "Fat": 3,
      "Na": 0,
      "Fiber": 210,
      "Carbs": 5,
      "Sugar": 13,
      "K": 5,
      "Vit": 190,
      "Score": 25
    },
    {
      "Brand": "Cap'n'Crunch",
      "Energy": "Q",
      "Protein": 120,
      "Fat": 1,
      "Na": 2,
      "Fiber": 220,
      "Carbs": 0,
      "Sugar": 12,
      "K": 12,
      "Vit": 35,
      "Score": 25
    },
    {
      "Brand": "Cheerios",
      "Energy": "G",
      "Protein": 110,
      "Fat": 6,
      "Na": 2,
      "Fiber": 290,
      "Carbs": 2,
      "Sugar": 17,
      "K": 1,
      "Vit": 105,
      "Score": 25
    },
    {
      "Brand": "Cinnamon_Toast_Crunch",
      "Energy": "G",
      "Protein": 120,
      "Fat": 1,
      "Na": 3,
      "Fiber": 210,
      "Carbs": 0,
      "Sugar": 13,
      "K": 9,
      "Vit": 45,
      "Score": 25
    },
    {
      "Brand": "Clusters",
      "Energy": "G",
      "Protein": 110,
      "Fat": 3,
      "Na": 2,
      "Fiber": 140,
      "Carbs": 2,
      "Sugar": 13,
      "K": 7,
      "Vit": 105,
      "Score": 25
    },
    {
      "Brand": "Cocoa_Puffs",
      "Energy": "G",
      "Protein": 110,
      "Fat": 1,
      "Na": 1,
      "Fiber": 180,
      "Carbs": 0,
      "Sugar": 12,
      "K": 13,
      "Vit": 55,
      "Score": 25
    },
    {
      "Brand": "Corn_Chex",
      "Energy": "R",
      "Protein": 110,
      "Fat": 2,
      "Na": 0,
      "Fiber": 280,
      "Carbs": 0,
      "Sugar": 22,
      "K": 3,
      "Vit": 25,
      "Score": 25
    },
    {
      "Brand": "Corn_Flakes",
      "Energy": "K",
      "Protein": 100,
      "Fat": 2,
      "Na": 0,
      "Fiber": 290,
      "Carbs": 1,
      "Sugar": 21,
      "K": 2,
      "Vit": 35,
      "Score": 25
    },
    {
      "Brand": "Corn_Pops",
      "Energy": "K",
      "Protein": 110,
      "Fat": 1,
      "Na": 0,
      "Fiber": 90,
      "Carbs": 1,
      "Sugar": 13,
      "K": 12,
      "Vit": 20,
      "Score": 25
    },
    {
      "Brand": "Count_Chocula",
      "Energy": "G",
      "Protein": 110,
      "Fat": 1,
      "Na": 1,
      "Fiber": 180,
      "Carbs": 0,
      "Sugar": 12,
      "K": 13,
      "Vit": 65,
      "Score": 25
    },
    {
      "Brand": "Cracklin'_Oat_Bran",
      "Energy": "K",
      "Protein": 110,
      "Fat": 3,
      "Na": 3,
      "Fiber": 140,
      "Carbs": 4,
      "Sugar": 10,
      "K": 7,
      "Vit": 160,
      "Score": 25
    },
    {
      "Brand": "Crispix",
      "Energy": "K",
      "Protein": 110,
      "Fat": 2,
      "Na": 0,
      "Fiber": 220,
      "Carbs": 1,
      "Sugar": 21,
      "K": 3,
      "Vit": 30,
      "Score": 25
    },
    {
      "Brand": "Crispy_Wheat_&_Raisins",
      "Energy": "G",
      "Protein": 100,
      "Fat": 2,
      "Na": 1,
      "Fiber": 140,
      "Carbs": 2,
      "Sugar": 11,
      "K": 10,
      "Vit": 120,
      "Score": 25
    },
    {
      "Brand": "Double_Chex",
      "Energy": "R",
      "Protein": 100,
      "Fat": 2,
      "Na": 0,
      "Fiber": 190,
      "Carbs": 1,
      "Sugar": 18,
      "K": 5,
      "Vit": 80,
      "Score": 25
    },
    {
      "Brand": "Froot_Loops",
      "Energy": "K",
      "Protein": 110,
      "Fat": 2,
      "Na": 1,
      "Fiber": 125,
      "Carbs": 1,
      "Sugar": 11,
      "K": 13,
      "Vit": 30,
      "Score": 25
    },
    {
      "Brand": "Frosted_Flakes",
      "Energy": "K",
      "Protein": 110,
      "Fat": 1,
      "Na": 0,
      "Fiber": 200,
      "Carbs": 1,
      "Sugar": 14,
      "K": 11,
      "Vit": 25,
      "Score": 25
    },
    {
      "Brand": "Frosted_Mini-Wheats",
      "Energy": "K",
      "Protein": 100,
      "Fat": 3,
      "Na": 0,
      "Fiber": 0,
      "Carbs": 3,
      "Sugar": 14,
      "K": 7,
      "Vit": 100,
      "Score": 25
    },
    {
      "Brand": "Fruit_&_Fibre_Dates,_Walnuts,_and_Oats",
      "Energy": "P",
      "Protein": 120,
      "Fat": 3,
      "Na": 2,
      "Fiber": 160,
      "Carbs": 5,
      "Sugar": 12,
      "K": 10,
      "Vit": 200,
      "Score": 25
    },
    {
      "Brand": "Fruitful_Bran",
      "Energy": "K",
      "Protein": 120,
      "Fat": 3,
      "Na": 0,
      "Fiber": 240,
      "Carbs": 5,
      "Sugar": 14,
      "K": 12,
      "Vit": 190,
      "Score": 25
    },
    {
      "Brand": "Fruity_Pebbles",
      "Energy": "P",
      "Protein": 110,
      "Fat": 1,
      "Na": 1,
      "Fiber": 135,
      "Carbs": 0,
      "Sugar": 13,
      "K": 12,
      "Vit": 25,
      "Score": 25
    },
    {
      "Brand": "Golden_Crisp",
      "Energy": "P",
      "Protein": 100,
      "Fat": 2,
      "Na": 0,
      "Fiber": 45,
      "Carbs": 0,
      "Sugar": 11,
      "K": 15,
      "Vit": 40,
      "Score": 25
    },
    {
      "Brand": "Golden_Grahams",
      "Energy": "G",
      "Protein": 110,
      "Fat": 1,
      "Na": 1,
      "Fiber": 280,
      "Carbs": 0,
      "Sugar": 15,
      "K": 9,
      "Vit": 45,
      "Score": 25
    },
    {
      "Brand": "Grape_Nuts_Flakes",
      "Energy": "P",
      "Protein": 100,
      "Fat": 3,
      "Na": 1,
      "Fiber": 140,
      "Carbs": 3,
      "Sugar": 15,
      "K": 5,
      "Vit": 85,
      "Score": 25
    },
    {
      "Brand": "Grape-Nuts",
      "Energy": "P",
      "Protein": 110,
      "Fat": 3,
      "Na": 0,
      "Fiber": 170,
      "Carbs": 3,
      "Sugar": 17,
      "K": 3,
      "Vit": 90,
      "Score": 25
    },
    {
      "Brand": "Great_Grains_Pecan",
      "Energy": "P",
      "Protein": 120,
      "Fat": 3,
      "Na": 3,
      "Fiber": 75,
      "Carbs": 3,
      "Sugar": 13,
      "K": 4,
      "Vit": 100,
      "Score": 25
    },
    {
      "Brand": "Honey_Graham_Ohs",
      "Energy": "Q",
      "Protein": 120,
      "Fat": 1,
      "Na": 2,
      "Fiber": 220,
      "Carbs": 1,
      "Sugar": 12,
      "K": 11,
      "Vit": 45,
      "Score": 25
    },
    {
      "Brand": "Honey_Nut_Cheerios",
      "Energy": "G",
      "Protein": 110,
      "Fat": 3,
      "Na": 1,
      "Fiber": 250,
      "Carbs": 1.5,
      "Sugar": 11.5,
      "K": 10,
      "Vit": 90,
      "Score": 25
    },
    {
      "Brand": "Honey-comb",
      "Energy": "P",
      "Protein": 110,
      "Fat": 1,
      "Na": 0,
      "Fiber": 180,
      "Carbs": 0,
      "Sugar": 14,
      "K": 11,
      "Vit": 35,
      "Score": 25
    },
    {
      "Brand": "Just_Right_Crunchy__Nuggets",
      "Energy": "K",
      "Protein": 110,
      "Fat": 2,
      "Na": 1,
      "Fiber": 170,
      "Carbs": 1,
      "Sugar": 17,
      "K": 6,
      "Vit": 60,
      "Score": 100
    },
    {
      "Brand": "Just_Right_Fruit_&_Nut",
      "Energy": "K",
      "Protein": 140,
      "Fat": 3,
      "Na": 1,
      "Fiber": 170,
      "Carbs": 2,
      "Sugar": 20,
      "K": 9,
      "Vit": 95,
      "Score": 100
    },
    {
      "Brand": "Kix",
      "Energy": "G",
      "Protein": 110,
      "Fat": 2,
      "Na": 1,
      "Fiber": 260,
      "Carbs": 0,
      "Sugar": 21,
      "K": 3,
      "Vit": 40,
      "Score": 25
    },
    {
      "Brand": "Life",
      "Energy": "Q",
      "Protein": 100,
      "Fat": 4,
      "Na": 2,
      "Fiber": 150,
      "Carbs": 2,
      "Sugar": 12,
      "K": 6,
      "Vit": 95,
      "Score": 25
    },
    {
      "Brand": "Lucky_Charms",
      "Energy": "G",
      "Protein": 110,
      "Fat": 2,
      "Na": 1,
      "Fiber": 180,
      "Carbs": 0,
      "Sugar": 12,
      "K": 12,
      "Vit": 55,
      "Score": 25
    },
    {
      "Brand": "Maypo",
      "Energy": "A",
      "Protein": 100,
      "Fat": 4,
      "Na": 1,
      "Fiber": 0,
      "Carbs": 0,
      "Sugar": 16,
      "K": 3,
      "Vit": 95,
      "Score": 25
    },
    {
      "Brand": "Muesli_Raisins,_Dates,_&_Almonds",
      "Energy": "R",
      "Protein": 150,
      "Fat": 4,
      "Na": 3,
      "Fiber": 95,
      "Carbs": 3,
      "Sugar": 16,
      "K": 11,
      "Vit": 170,
      "Score": 25
    },
    {
      "Brand": "Muesli_Raisins,_Peaches,_&_Pecans",
      "Energy": "R",
      "Protein": 150,
      "Fat": 4,
      "Na": 3,
      "Fiber": 150,
      "Carbs": 3,
      "Sugar": 16,
      "K": 11,
      "Vit": 170,
      "Score": 25
    },
    {
      "Brand": "Mueslix_Crispy_Blend",
      "Energy": "K",
      "Protein": 160,
      "Fat": 3,
      "Na": 2,
      "Fiber": 150,
      "Carbs": 3,
      "Sugar": 17,
      "K": 13,
      "Vit": 160,
      "Score": 25
    },
    {
      "Brand": "Multi-Grain_Cheerios",
      "Energy": "G",
      "Protein": 100,
      "Fat": 2,
      "Na": 1,
      "Fiber": 220,
      "Carbs": 2,
      "Sugar": 15,
      "K": 6,
      "Vit": 90,
      "Score": 25
    },
    {
      "Brand": "Nut&Honey_Crunch",
      "Energy": "K",
      "Protein": 120,
      "Fat": 2,
      "Na": 1,
      "Fiber": 190,
      "Carbs": 0,
      "Sugar": 15,
      "K": 9,
      "Vit": 40,
      "Score": 25
    },
    {
      "Brand": "Nutri-Grain_Almond-Raisin",
      "Energy": "K",
      "Protein": 140,
      "Fat": 3,
      "Na": 2,
      "Fiber": 220,
      "Carbs": 3,
      "Sugar": 21,
      "K": 7,
      "Vit": 130,
      "Score": 25
    },
    {
      "Brand": "Nutri-grain_Wheat",
      "Energy": "K",
      "Protein": 90,
      "Fat": 3,
      "Na": 0,
      "Fiber": 170,
      "Carbs": 3,
      "Sugar": 18,
      "K": 2,
      "Vit": 90,
      "Score": 25
    },
    {
      "Brand": "Oatmeal_Raisin_Crisp",
      "Energy": "G",
      "Protein": 130,
      "Fat": 3,
      "Na": 2,
      "Fiber": 170,
      "Carbs": 1.5,
      "Sugar": 13.5,
      "K": 10,
      "Vit": 120,
      "Score": 25
    },
    {
      "Brand": "Post_Nat._Raisin_Bran",
      "Energy": "P",
      "Protein": 120,
      "Fat": 3,
      "Na": 1,
      "Fiber": 200,
      "Carbs": 6,
      "Sugar": 11,
      "K": 14,
      "Vit": 260,
      "Score": 25
    },
    {
      "Brand": "Product_19",
      "Energy": "K",
      "Protein": 100,
      "Fat": 3,
      "Na": 0,
      "Fiber": 320,
      "Carbs": 1,
      "Sugar": 20,
      "K": 3,
      "Vit": 45,
      "Score": 100
    },
    {
      "Brand": "Puffed_Rice",
      "Energy": "Q",
      "Protein": 50,
      "Fat": 1,
      "Na": 0,
      "Fiber": 0,
      "Carbs": 0,
      "Sugar": 13,
      "K": 0,
      "Vit": 15,
      "Score": 0
    },
    {
      "Brand": "Puffed_Wheat",
      "Energy": "Q",
      "Protein": 50,
      "Fat": 2,
      "Na": 0,
      "Fiber": 0,
      "Carbs": 1,
      "Sugar": 10,
      "K": 0,
      "Vit": 50,
      "Score": 0
    },
    {
      "Brand": "Quaker_Oat_Squares",
      "Energy": "Q",
      "Protein": 100,
      "Fat": 4,
      "Na": 1,
      "Fiber": 135,
      "Carbs": 2,
      "Sugar": 14,
      "K": 6,
      "Vit": 110,
      "Score": 25
    },
    {
      "Brand": "Raisin_Bran",
      "Energy": "K",
      "Protein": 120,
      "Fat": 3,
      "Na": 1,
      "Fiber": 210,
      "Carbs": 5,
      "Sugar": 14,
      "K": 12,
      "Vit": 240,
      "Score": 25
    },
    {
      "Brand": "Raisin_Nut_Bran",
      "Energy": "G",
      "Protein": 100,
      "Fat": 3,
      "Na": 2,
      "Fiber": 140,
      "Carbs": 2.5,
      "Sugar": 10.5,
      "K": 8,
      "Vit": 140,
      "Score": 25
    },
    {
      "Brand": "Raisin_Squares",
      "Energy": "K",
      "Protein": 90,
      "Fat": 2,
      "Na": 0,
      "Fiber": 0,
      "Carbs": 2,
      "Sugar": 15,
      "K": 6,
      "Vit": 110,
      "Score": 25
    },
    {
      "Brand": "Rice_Chex",
      "Energy": "R",
      "Protein": 110,
      "Fat": 1,
      "Na": 0,
      "Fiber": 240,
      "Carbs": 0,
      "Sugar": 23,
      "K": 2,
      "Vit": 30,
      "Score": 25
    },
    {
      "Brand": "Rice_Krispies",
      "Energy": "K",
      "Protein": 110,
      "Fat": 2,
      "Na": 0,
      "Fiber": 290,
      "Carbs": 0,
      "Sugar": 22,
      "K": 3,
      "Vit": 35,
      "Score": 25
    },
    {
      "Brand": "Shredded_Wheat",
      "Energy": "N",
      "Protein": 80,
      "Fat": 2,
      "Na": 0,
      "Fiber": 0,
      "Carbs": 3,
      "Sugar": 16,
      "K": 0,
      "Vit": 95,
      "Score": 0
    },
    {
      "Brand": "Shredded_Wheat_'n'Bran",
      "Energy": "N",
      "Protein": 90,
      "Fat": 3,
      "Na": 0,
      "Fiber": 0,
      "Carbs": 4,
      "Sugar": 19,
      "K": 0,
      "Vit": 140,
      "Score": 0
    },
    {
      "Brand": "Shredded_Wheat_spoon_size",
      "Energy": "N",
      "Protein": 90,
      "Fat": 3,
      "Na": 0,
      "Fiber": 0,
      "Carbs": 3,
      "Sugar": 20,
      "K": 0,
      "Vit": 120,
      "Score": 0
    },
    {
      "Brand": "Smacks",
      "Energy": "K",
      "Protein": 110,
      "Fat": 2,
      "Na": 1,
      "Fiber": 70,
      "Carbs": 1,
      "Sugar": 9,
      "K": 15,
      "Vit": 40,
      "Score": 25
    },
    {
      "Brand": "Special_K",
      "Energy": "K",
      "Protein": 110,
      "Fat": 6,
      "Na": 0,
      "Fiber": 230,
      "Carbs": 1,
      "Sugar": 16,
      "K": 3,
      "Vit": 55,
      "Score": 25
    },
    {
      "Brand": "Strawberry_Fruit_Wheats",
      "Energy": "N",
      "Protein": 90,
      "Fat": 2,
      "Na": 0,
      "Fiber": 15,
      "Carbs": 3,
      "Sugar": 15,
      "K": 5,
      "Vit": 90,
      "Score": 25
    },
    {
      "Brand": "Total_Corn_Flakes",
      "Energy": "G",
      "Protein": 110,
      "Fat": 2,
      "Na": 1,
      "Fiber": 200,
      "Carbs": 0,
      "Sugar": 21,
      "K": 3,
      "Vit": 35,
      "Score": 100
    },
    {
      "Brand": "Total_Raisin_Bran",
      "Energy": "G",
      "Protein": 140,
      "Fat": 3,
      "Na": 1,
      "Fiber": 190,
      "Carbs": 4,
      "Sugar": 15,
      "K": 14,
      "Vit": 230,
      "Score": 100
    },
    {
      "Brand": "Total_Whole_Grain",
      "Energy": "G",
      "Protein": 100,
      "Fat": 3,
      "Na": 1,
      "Fiber": 200,
      "Carbs": 3,
      "Sugar": 16,
      "K": 3,
      "Vit": 110,
      "Score": 100
    },
    {
      "Brand": "Triples",
      "Energy": "G",
      "Protein": 110,
      "Fat": 2,
      "Na": 1,
      "Fiber": 250,
      "Carbs": 0,
      "Sugar": 21,
      "K": 3,
      "Vit": 60,
      "Score": 25
    },
    {
      "Brand": "Trix",
      "Energy": "G",
      "Protein": 110,
      "Fat": 1,
      "Na": 1,
      "Fiber": 140,
      "Carbs": 0,
      "Sugar": 13,
      "K": 12,
      "Vit": 25,
      "Score": 25
    },
    {
      "Brand": "Wheat_Chex",
      "Energy": "R",
      "Protein": 100,
      "Fat": 3,
      "Na": 1,
      "Fiber": 230,
      "Carbs": 3,
      "Sugar": 17,
      "K": 3,
      "Vit": 115,
      "Score": 25
    },
    {
      "Brand": "Wheaties",
      "Energy": "G",
      "Protein": 100,
      "Fat": 3,
      "Na": 1,
      "Fiber": 200,
      "Carbs": 3,
      "Sugar": 17,
      "K": 3,
      "Vit": 110,
      "Score": 25
    },
    {
      "Brand": "Wheaties_Honey_Gold",
      "Energy": "G",
      "Protein": 110,
      "Fat": 2,
      "Na": 1,
      "Fiber": 200,
      "Carbs": 1,
      "Sugar": 16,
      "K": 8,
      "Vit": 60,
      "Score": 25
    }
  ],
};

const getters = {
  getData: state => {
    return state.data;
  },
  getHeaders: state => {
    var headers = [];
    var obj = Object.keys(state.data[0]);
    for (var i = 0; i < obj.length; i++) {
      headers.push({ text: obj[i].toString(), value: obj[i].toString(), left: true, })
    }
    return headers;
  },
};

const mutations = {
  setData: (state, payload) => {
    state.data = payload;
  },
};

const actions = {
  setData: ({ commit }, payload) => {
    commit('setData', payload);
  },
};

export default {
  state,
  getters,
  mutations,
  actions,
};
